services:
  # 1. The Database
  mysql:
    image: mariadb:10.5
    container_name: mysql
    restart: unless-stopped
    expose:
      - "3306"
    volumes_from:
      - sqlscript
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
      - mysql:/var/lib/mysql:rw
      #- ./app/Database/tables.sql:/docker-entrypoint-initdb.d/1.sql
      #- ./app/Database/constraints.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - ospos_network

  sqlscript:
    image: jekkos/opensourcepos:sql-master
    command: /bin/sh -c 'exit 0'

  # 3. The OSPOS App
  ospos:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERID=${USERID}
        - GROUPID=${GROUPID}

    #image: jekkos/opensourcepos:master
    container_name: ospos_app
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - CI_ENVIRONMENT=${CI_ENVIRONMENT}
      - FORCE_HTTPS=false
      - MYSQL_HOST_NAME=mysql
      - MYSQL_USERNAME=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DB_NAME=${DB_NAME}
      - TZ=${TIMEZONE}
    networks: 
      - ospos_network
    volumes:
      - ./uploads:/app/public/uploads
      - ./logs:/app/writable/logs

networks:
  ospos_network:
    driver: bridge

volumes:
  uploads:
    driver: local
  logs:
    driver: local
  mysql:
    driver: local
  mysql_data:
